include:
  - project: syseleven/gitlab-ci-templates
    ref: 3.29.3
    file: job-templates/TerraformValidate.yml
  - project: syseleven/gitlab-ci-templates
    ref: 3.29.3
    file: job-templates/TerraformFormat.yml
  - project: syseleven/gitlab-ci-templates
    ref: 3.29.3
    file: MarkdownLint.yml

stages:
  - test

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

default:
  retry:
    max: 2
    when:
      - runner_system_failure

##################################################################
#                            JOBS                                #
##################################################################

terraform-format:
  extends:
    - .terraform-format

terraform-validate:
  extends:
    - .terraform-validate


tfplugindocs:
  image: golang:1.22.3
  before_script:
    - apt update && apt install -y unzip
    - wget -O /tmp/tfplugindocs.zip https://github.com/hashicorp/terraform-plugin-docs/releases/download/v0.19.2/tfplugindocs_0.19.2_linux_amd64.zip
    - unzip -p /tmp/tfplugindocs.zip tfplugindocs > /usr/local/bin/tfplugindocs
    - chmod 0555 /usr/local/bin/tfplugindocs
  script:
    - tfplugindocs
    - if [[ ! -z "$(git status -s)" ]]; then echo "Found documentation files. Please run tfplugindocs locally and commit changes." && git diff && exit 1; fi
